<?php

namespace App\Entity;

use Money\Money;

class Product
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var Money
     */
    private $price;

    /**
     * @param int $id
     * @param int $price
     */
    public function __construct(int $id, int $price)
    {
        /*
         * In normal circumstances there would be an id autogenerated by Doctrine or UUID, but since I need to query
         * for product using its id, I decided the simplest solution here is to set integer id by hand
         */
        $this->id = $id;
        $this->price = Money::PLN($price);
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return Money
     */
    public function getPrice(): Money
    {
        return $this->price;
    }

    /**
     * @param Money $price
     */
    public function setPrice(Money $price): void
    {
        $this->price = $price;
    }
}